title: cppdocs
description: archive docs
theme: just-the-docs

url: https://yutijang.github.io/cppdocs

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

compress_html:
  ignore:
    envs: all

nav_enabled: false
