title: cppdocs
description: yutijang's archive cpp docs
theme: just-the-docs

favicon_ico: "/assets/images/favicon.ico"

url: https://yutijang.github.io
baseurl: /cppdocs

nav_error_report: true

permalink: pretty

author: yutijang
github_username: yutijang
email: yutijang@gmail.com

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

compress_html:   
   ignore:
     envs: all

nav_enabled: true

back_to_top: true
back_to_top_text: "Lên đầu trang"
footer_content: ''

plugins:  
  - jekyll-seo-tag
  - jekyll-include-cache

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
