title: cppdocs
description: archive docs
theme: just-the-docs

url: https://yutijang.github.io/cppdocs

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all

nav_enabled: true

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap
