title: cppdocs
description: yutijang's archive cpp docs
theme: just-the-docs

# url: https://yutijang.github.io/cppdocs
author: yutijang
github_username: yutijang
email: yutijang@gmail.com

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

compress_html:
   ignore:
     envs: all

nav_enabled: true

plugins:  
  - jekyll-seo-tag
  - jekyll-include-cache
