name: Backup Website

on:
  schedule:
    - cron: '0 20 * * *'  # Thực hiện vào lúc 03:00 UTC mỗi ngày
  workflow_dispatch:  # Thêm dòng này để hỗ trợ chạy thủ công

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Check for changes
        id: changes
        run: |
          git fetch origin main
          if git diff --quiet origin/main; then
            echo "::set-output name=changed::false"
          else
            echo "::set-output name=changed::true"
          fi

      - name: Debugging: Output changed status
        run: echo "Changed: ${{ steps.changes.outputs.changed }}"

      - name: Create backup branch
        if: steps.changes.outputs.changed == 'true'
        run: |
          echo "Creating backup branch..."
          git checkout -b backup
          git add .
          git commit -m "Automated backup"
          git push origin backup
